//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanSachMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiBanh
    {
        public LoaiBanh()
        {
            this.DanhsachBanhs = new HashSet<DanhsachBanh>();
        }
    
        public int MaLoai { get; set; }
        public string TenLoai { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<DanhsachBanh> DanhsachBanhs { get; set; }
    }
}
